### PR TITLE
Added and improved circuit methods

### PR DESCRIPTION
**Pull request by tmjo**

### CODE REVIEW

**Comment by olalid** [comment]
A question, since I do not yet have a car to test the behaviour with:
My interpretation has been that the "max circuit current" is the same value you can set manually in the easee app, and it is a "hard" limit which the charger will not go above.
The dynamic current is on the other hand an additional limit that can be set by a load balancer.
Which should mean in practice that the lower of the 2 values is what actually limits the current.
Does that seem right?

**Comment by tmjo** [comment]
> A question, since I do not yet have a car to test the behaviour with:
> My interpretation has been that the "max circuit current" is the same value you can set manually in the easee app, and it is a "hard" limit which the charger will not go above.
> The dynamic current is on the other hand an additional limit that can be set by a load balancer.
> Which should mean in practice that the lower of the 2 values is what actually limits the current.
> Does that seem right?

Hi Ola,

I believe your interpretation is correct in a way, but there is a "ratedCurrent" for circuits which is "hard" and is not to be touched by the user. It seems to be the one being set during first setup (usually by the authorized installer). So my guess is that this is the final limit which will not be exceeded in any case.

Then, dynamicCurrent and maxCurrent seems to do the same thing when there is only one charger. I have not tested with several chargers, but my interpretation is that maxCurrent is your custom limit for the circuit while dynamicCurrent is how much the specific charger should be allowed from this circuit. I think it is the one used by Tibber, but not sure.

**Comment by fondberg** [comment]
@tmjo can you rebase on current master?

**Comment by tmjo** [comment]
> @tmjo can you rebase on current master?

Sure. I think my PRs are up to date with current master, but do you mean that I should merge them to my master before issuing the PRs?

**Comment by fondberg** [comment]
It doesnt seem to be up to date with this master as @olalid PR contained some of your stuff.

**Comment by tmjo** [comment]
Humm. I rebased everything this morning, and had the PR from olalid. But perhaps I am doing something else wrong?? I suggested some minor improvements to the PR from olalid as well as adding an additional function.

**Comment by tmjo** [comment]
Could it be that I added several commits in the same PR? I kept doing improvements (in my mind that is, hehe) and just committed them to my local branch. Though I had to do new PR to push them to yours, but I discovered they entered directly when I had an open PR already. Probably should have made new branch for that. Sorry for the mess.

**Comment by fondberg** [comment]
You can do a git fetch upstream && git merge upstream master

**Comment by tmjo** [comment]
I tried both with git cli and git desktop, they claim it is the same. Also checked manually, they are already reabased to include the latest commits on your master. Also my master on web says there are no differences and both branches were made from that updated master. Not sure what else I can do?

**Comment by tmjo** [comment]
I verified that my master is currently in synch with yours, merged my branches into my master and created a new PR. Will close this one. Hope it helps.

**Pull request closed without merging**
